CREATE TABLE FOLLOWME."ROLE"
  (
    ID_ROLE          NUMBER(2,0) NOT NULL ENABLE,
    ROLE_DESCRIPTION VARCHAR2(20 BYTE),
    CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID_ROLE")
  ) ;
CREATE TABLE "FOLLOWME"."USER"
  (
    "ID_USER"      NUMBER(5,0) NOT NULL ENABLE,
    "USERNAME"     VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "PASSWORD"     VARCHAR2(32 BYTE) NOT NULL ENABLE,
    "SALT"         VARCHAR2(32 BYTE) NOT NULL ENABLE,
    "ID_ROLE"      NUMBER(2,0),
    "FLAG_DELETED" NUMBER(1,0),
    CONSTRAINT "USER_PK" PRIMARY KEY ("ID_USER"),
    CONSTRAINT "USER_ROLE_FK" FOREIGN KEY ("ID_ROLE") REFERENCES "FOLLOWME"."ROLE" ("ID_ROLE") ON
  DELETE SET NULL ENABLE
  ) ;
CREATE TABLE "FOLLOWME"."TOKEN"
  (
    "ID_TOKEN" NUMBER(15,0) NOT NULL ENABLE,
    "ID_USER"  NUMBER(5,0) NOT NULL ENABLE,
    "TOKEN"    VARCHAR2(32 BYTE),
    "EXPIRATION_TIME" DATE,
    CONSTRAINT "TOKEN_PK" PRIMARY KEY ("ID_TOKEN"),
    CONSTRAINT "TOKEN_USER_FK1" FOREIGN KEY ("ID_USER") REFERENCES "FOLLOWME"."USER" ("ID_USER") ON
  DELETE CASCADE ENABLE
  );
CREATE TABLE POSITION
  (
    ID_USER NUMBER(5, 0) NOT NULL,
    MOMENT DATE NOT NULL,
    LATITUDE  NUMBER(9, 6) NOT NULL,
    LONGITUDE NUMBER(9, 6) NOT NULL ,
    CONSTRAINT POSITION_PK PRIMARY KEY ( ID_USER, MOMENT ) ENABLE,
    CONSTRAINT "POSITION_USER_FK" FOREIGN KEY ("ID_USER") REFERENCES "FOLLOWME"."USER" ("ID_USER") ON
  DELETE CASCADE ENABLE
  ) ;
CREATE SEQUENCE SEQ_USER INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_TOKEN INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_ROLE INCREMENT BY 1 START WITH 1 MINVALUE 1;